"""empty message

Revision ID: c32a2ab5645f
Revises: 7ddfafa91732
Create Date: 2024-12-18 14:39:59.676640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c32a2ab5645f'
down_revision = '7ddfafa91732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.alter_column('views',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.alter_column('views',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
